### PR TITLE
Implementing filters in sqlalchemy admin

### PR DESCRIPTION
**Pull request by lucasvo**
- [ ] @wojcikstefan should add whatever we merge here to the upstream PR (https://github.com/syrusakbary/Flask-SuperAdmin/pull/150)

### CODE REVIEW

**Comment by wojcikstefan** [comment]
@lucasvo could you add at least one test to flask_superadmin/tests/test_sqlamodel.py as a proof it works at least for the simplest cases?

**Comment by philfreo** [comment]
+1 and also be sure to make an upstream PR

**Comment by lucasvo** [comment]
@philfreo I think filters are not implemented in "upstream". That's the feature we built ourselves, we should submit this along with the pull request for the original feature that stefan implemented for mongoengine.

**Comment by wojcikstefan** [comment]
There's a WIP PR open for field filters in the upstream repo: https://github.com/syrusakbary/Flask-SuperAdmin/pull/150

**Comment by wojcikstefan** [comment]
@lucasvo see https://github.com/syrusakbary/Flask-SuperAdmin/pull/150/commits/2237ca55fa62d1a27d0fb9a11b2a98698d19a885 for an example of a simple unit test for MongoEngine

**Pull request merged**
